import "./globals.css";

import type { Metadata, Viewport } from "next";
import { Montserrat } from "next/font/google";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nexalis International - Oil & Gas",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: "#af2626",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
